// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersion("2019.0.0.0")]
