// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("SortedList")]
[assembly: AssemblyProductAttribute("Spreads")]
[assembly: AssemblyDescriptionAttribute("Spreads")]
[assembly: AssemblyVersionAttribute("0.0.4")]
[assembly: AssemblyFileVersionAttribute("0.0.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.4";
    }
}
