# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.1 SDK
    inputs:
      version: '3.1.x'
      packageType: sdk

#  - script: dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -f netcoreapp3.0 -c Debug  --filter TestCategory=CI -v m
#    displayName: 'Test Debug netcoreapp3.0'

  - script: dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -f netcoreapp3.0 -c Release  --filter TestCategory=CI -v m
    displayName: 'Test Release netcoreapp3.0'

- job: Mac
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.1 SDK
    inputs:
      version: '3.1.x'
      packageType: sdk

#  - script: dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -f netcoreapp3.0 -c Debug  --filter TestCategory=CI -v m
#    displayName: 'Test Debug netcoreapp3.0'

  - script: dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -f netcoreapp3.0 -c Release  --filter TestCategory=CI -v m
    displayName: 'Test Release netcoreapp3.0'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.1 SDK
    inputs:
      version: '3.1.x'
      packageType: sdk

#  - script: dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -f netcoreapp3.0 -c Debug  --filter TestCategory=CI -v m
#    displayName: 'Test Debug netcoreapp3.0'

  - script: dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -f netcoreapp3.0 -c Release  --filter TestCategory=CI -v m
    displayName: 'Test Release netcoreapp3.0'


