// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Spreads.Extensions")]
[assembly: AssemblyProductAttribute("Spreads")]
[assembly: AssemblyDescriptionAttribute("Spreads")]
[assembly: AssemblyVersionAttribute("0.0.6")]
[assembly: AssemblyFileVersionAttribute("0.0.6")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.6";
    }
}
