// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Spreads.Extensions")]
[assembly: AssemblyProductAttribute("Spreads")]
[assembly: AssemblyDescriptionAttribute("Spreads")]
[assembly: AssemblyVersionAttribute("0.5.1")]
[assembly: AssemblyFileVersionAttribute("0.5.1")]
[assembly: AssemblyCopyrightAttribute("(c) Victor Baybekov 2015")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.1";
    }
}
