// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Spreads.Extensions")]
[assembly: AssemblyProductAttribute("Spreads")]
[assembly: AssemblyDescriptionAttribute("Spreads")]
[assembly: AssemblyVersionAttribute("0.3.1")]
[assembly: AssemblyFileVersionAttribute("0.3.1")]
[assembly: AssemblyCopyrightAttribute("(c) Victor Baybekov 2015")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.3.1";
    }
}
