// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// <auto-generated/>

using System;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: CLSCompliant(false)]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]

namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.8.0";
    }
}
