// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Spreads.Core")]
[assembly: AssemblyProductAttribute("Spreads")]
[assembly: AssemblyDescriptionAttribute("Spreads")]
[assembly: AssemblyVersionAttribute("0.2.3")]
[assembly: AssemblyFileVersionAttribute("0.2.3")]
[assembly: AssemblyCopyrightAttribute("(c) Victor Baybekov 2015")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.3";
    }
}
