name: Build & Test Spreads.Core

on:
  push:
    branches: [ main ]
  release:
    types:
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  test_net60:
    name: Test .NET 6.0 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Test 6.0 Debug
      run: dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -f net6.0 -c Debug --filter TestCategory=CI -v m
    - name: Test 6.0 Release
      run: dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -f net6.0 -c Release --filter TestCategory=CI -v m


  test_net48:
    name: Test .NET 4.8
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Test .NET 4.8
        run: |
          dotnet restore tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj
          msbuild tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj /p:Configuration=Release
          dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -f net48 -c Release --no-build --no-restore --filter TestCategory=CI -v m
